NewBieTonTeam5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('custom_auth.urls')),
    path('', include('greeting.urls')),
    #path(summernote/', include('django_summernote.urls')),
    path('market/', include('puppy_sale.urls')),
    path('community/', include('community.urls')),
]

community/urls.py
from django.urls import path
from .views import review, PostListView, PostDetailView, PostCreateView, ReviewCreateView, ReviewDetailView, review_comment_create, ReviewListView


urlpatterns = [
    path('board', PostListView.as_view(), name='board'),
    path('board/<int:pk>', PostDetailView.as_view(), name='board_detail'),
    path('board/new', PostCreateView.as_view(), name='board_create'),
    path('review', ReviewListView.as_view(), name='review'),
    path('review/new', ReviewCreateView.as_view(), name='review_create'),
    path('review/<int:pk>', ReviewDetailView.as_view(), name='review_detail'),
    path('review/<int:pk>/comments', review_comment_create, name='review_comment_create'),
#    path('post/<int:pk>/comments', post_comment_create, name='post_comment_create'),
]

greeting/urls.py
from django.urls import path

from .views import welcome
from .views import signup
from .views import main

urlpatterns = [
    path('', welcome, name='welcome'),
    path('main/', main, name='main'),
    path('signup/', signup, name='signup'),
]

community/models.py
from django.db import models
from django.conf import settings

from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse

SCORES = (
    (0, '☆☆☆☆☆'),
    (1, '★☆☆☆☆'),
    (2, '★★☆☆☆'),
    (3, '★★★☆☆'),
    (4, '★★★★☆'),
    (5, '★★★★★'),
)

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=30, default='') 
    title = models.CharField(max_length=100, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='글 쓴 날짜')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정한 날짜')
    hits = models.IntegerField(default=0, blank=True) 
    
    class Meta:
        ordering = ['created_at']
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('board_detail', args=[self.id])

class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=30, default="")
    
    title = models.CharField(max_length=100, blank=False, null=False)
    score = models.IntegerField(choices=SCORES, default=0)
    
    reviewable_id = models.PositiveIntegerField(default=1)
    reviewable_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    reviewable_name = models.CharField(max_length=30, default="")
    reviewable = GenericForeignKey('reviewable_type', 'reviewable_id')
    
    description = models.TextField(default='')
    
    def get_absolute_url(self):
        return reverse('review_detail', args=[self.id])
    

class Comment(models.Model):
    commentable_id = models.PositiveIntegerField(default=1)
    commentable_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=30, default="")
    commentable = GenericForeignKey('commentable_type', 'commentable_id')
    
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(verbose_name='')
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.title
    

community/forms.py
from django import forms
from .models import Comment

class CommentCreationForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'cols': 80, 'rows': 20}),
        }

community/views.py
from django import forms
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.contrib.contenttypes.models import ContentType


from .models import Post, Comment, Review
from puppy_sale.models import PetSupply 

from .forms import CommentCreationForm

### Post ###
class PostListView(ListView):
    model = Post
    paginate_by = 10
    template_name = 'community/board.html'
    context_object_name = 'post_list'

    queryset = Post.objects.all()

    
class PostDetailView(DetailView):
    model = Post
    template_name = 'community/board_detail.html'
    context_object_name = 'post'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(commentable_type__model='Post', commentable_id=self.kwargs['pk'])
        return context
    
    def get_object(self):
        post = super().get_object()
        post.hits += 1
        post.save()
        self.view_count = post.hits
        return post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'community/board_create.html'
    fields = ['title', 'content']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.author_name = self.request.user.real_name
        
        return super().form_valid(form)
   

### Review ###
class ReviewListView(ListView):
    model = Review
    paginate_by = 10
    template_name = 'community/review.html'
    context_object_name = 'review_list'

    queryset = Review.objects.all()
    
class ReviewDetailView(DetailView):
    model = Review
    template_name = 'community/review_detail.html'
    context_object_name = 'review'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(commentable_type__model='review', commentable_id=self.kwargs['pk'])
        return context
    
    
class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = "community/reviewWrite.html"
    
    fields = ['reviewable_id', 'reviewable_name', 'title', 'score', 'description']        
    
    def get_form(self, *args, **kwargs):
        form = super(ReviewCreateView, self).get_form(*args, **kwargs)
        form.fields['reviewable_id'] = \
            forms.ChoiceField(choices=[
                (pet_supply.pk, pet_supply.name) for pet_supply in PetSupply.objects.all()])
        form.fields['reviewable_name'].widget = forms.HiddenInput()

        return form
    
    def form_valid(self, form):
        form.instance.reviewable_type = ContentType.objects.get_for_model(PetSupply)
        
        form.instance.author = self.request.user
        form.instance.author_name = self.request.user.real_name
        
        return super().form_valid(form)
    
def review_comment_create(request, pk):
    if request.method == 'POST':
        form = CommentCreationForm(request.POST)

        if not form.is_valid():
            return redirect("review_detail", pk=pk)

        comment = form.save(commit=False)
        comment.author = request.user
        comment.author_name = request.user.real_name
        
        comment.commentable_id = pk
        comment.commentable_type = ContentType.objects.get_for_model(Review)
        
        comment.save()
        
        return redirect('review_detail', pk=pk)
        
    return redirect('/')

def review(request):
    pass

community/templates/community/board.html
<!DOCTYPE html>
<html lang= "ko">
    <head>
        <script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">

        <title>상세 페이지</title>
        
    </head>
    <body>
        <div class="container">
        <div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading">게시글 목록</div>

  <!-- Table -->
  <table class="table">
    <thead>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>글쓴이</th>
            <th>날짜</th>
            <th>조회수</th>
        </tr>
    </thead>
    <tbody>
        {% if post_list %}
            {% for post in post_list %}
        <tr>
            <td>{{ post.id }}</td>
            <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
            <td>{{ post.author_name }}</td>
            <td>{{ post.created_at }}</td>
            <td>{{ post.hits }}</td>
        </tr>
            {% endfor %}
        {% else %}
        <p>
            게시글이 아직 없습니다.
        </p>
        {% endif %}
    </tbody>
</table>
</div>
<nav>
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
            </div>
    </body>
    </html>

community/templates/community/board_create.html
<!DOCTYPE html>
<html>
  <head lang="en">
    <meta charset="UTF-8">
    <title>1. Basic</title>
    <script src="../lib/jquery/dist/jquery.js"></script>
    <script src='../lib/markdown-it/dist/markdown-it.js'></script>
    <script src="../lib/to-mark/dist/to-mark.js"></script>
    <script src="../lib/tui-code-snippet/dist/tui-code-snippet.js"></script>
    <script src="../lib/codemirror/lib/codemirror.js"></script>
    <script src="../lib/highlightjs/highlight.pack.js"></script>
    <script src="../lib/squire-rte/build/squire-raw.js"></script>
    <link rel="stylesheet" href="../lib/codemirror/lib/codemirror.css">
    <link rel="stylesheet" href="../lib/highlightjs/styles/github.css">
    <link rel="stylesheet" href="./explain.css">
  </head>
  <body>
    <div class="code-html">
      <script src="../dist/tui-editor-Editor.js"></script>
      <link rel="stylesheet" href="../dist/tui-editor.css">
      <link rel="stylesheet" href="../dist/tui-editor-contents.css">

      <div id="editSection" style="box-sizing": border-box; height:400px;>
      <form action='/community/board/new' method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>
        제출
    </button>
</form>
        </div>
    </div>
    <script class="code-js">
      var editor = new tui.Editor({
        el: document.querySelector('#editSection'),
        initialEditType: 'markdown',
        previewStyle: 'vertical',
        height: '300px'
      });
    </script>
  </body>
</html>
<!--
<form action='/community/board/new' method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>
        제출
    </button>
</form> --!>

community/templates/community/board_detail.html
<!DOCTYPE html>
<html lang= "ko">
    <head>
        <script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">

        <title>상세 페이지</title>
        
    </head>
    <body>
        <div class="container">
            <span class="label label-default">작성자: {{ post.author_name }}</span>
            <span class="label label-primary">작성날짜: {{ post.created_at }}</span>
            <span class="label label-danger">조회수: {{ post.hits }}</span>

            <div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h2>{{ post.title }}</h2>
        <p>{{ post.content }}</p>
      </div>
    </div>
  </div>
</div>

        </div>
    </body>
</html>

community/templates/community/reviewWrite.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>후기 남기기</title>


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    body {
      padding-top: 56px;
    }
  </style>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <style>

    .input_title {
      width: 90%;
      margin-bottom: 10px;
    }

    .input_content {
      width: 90%;
      height: 400px;
    }

  </style>
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Puppy Lovers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<!-- Page Content -->
<div class="container">

  <div class="row">

    <div class="col-lg-3">

      <h1 class="my-4">글쓰기</h1>
      <!-- <div class="list-group">
        <a href="#" class="list-group-item">Category 1</a>
        <a href="#" class="list-group-item">Category 2</a>
        <a href="#" class="list-group-item">Category 3</a>
      </div> -->

    </div>
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">

      <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <!-- <div class="carousel-item active">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
          </div> -->
          <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div class="row">
        <form action="{% url 'review_create' %}" method="post">
        <div class="col-lg-8 col-md-15 mb-7">
          <div class="card h-200">
            <!--<a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>-->
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">후기 작성</a>
              </h4>

              <div>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">
                    제출
                  </button>
              </div>

            </div>
            <div class="card-footer">

            </div>
          </div>
        </div>
      </div>
    </form>
      <!-- /.row -->

    </div>
    <!-- /.col-lg-9 -->

  </div>
  <!-- /.row .-->
  <div style="text-align:right">
    <button style="text-align:right; margin-top:10px; margin-bottom:10px" type="button" class="btn btn-primary">
      저장
    </button>
  </div>

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy;</p>
  </div>
  <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
    <!--
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js">
-->
</script>

    
<script>
$(document).ready(function() {
    var hidden_value = $( "#id_reviewable_id option:selected" ).text();
    $("#id_reviewable_name").val(hidden_value);

     $( "#id_reviewable_id" ).change(function() {
        var hidden_value = $( "#id_reviewable_id option:selected" ).text();
        $("#id_reviewable_name").val(hidden_value);
    });

});
    
    </script>

</body>

</html>

community/templates/community/review_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/font-iropke-batang/1.2/font-iropke-batang.css">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pet Sale</title>


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    body {
      padding-top: 56px;
    }

    .reply {
      width : 85%;
      height: 200px;
    }
  </style>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Puppy Lovers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Page Content -->
<div class="container">

  <div class="row">

    <div class="col-lg-3">

      <h1 class="my-4">후기 페이지</h1>

    </div>
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">

      <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div class="row">

        <div class="col-lg-4 col-md-15 mb-4">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://placeimg.com/500/200/any" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                제목 : {{review.title}}
              </h4>
             <h4 class="card-title">
                품명 : {{review.reviewable_name}}
              </h4>
             <h4 class="card-title">
                후기 : {{review.description}}
              </h4>
              <h4>
                평점 : {{review.get_score_display}}  
              </h4>  
                
              <p class="card-text"></p>
            </div>
            <div class="card-footer">

            </div>
          </div>
        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.col-lg-9 -->

  </div>
    
  <!-- 댓글 리스트 출력 -->
  {% for comment in comments %}
  <div>
    <h4>{{comment.author}}</h4>
    <p>{{comment.text}}</p>
  </div>
  {% endfor%}
  <!-- /.row .-->
    {% if user.is_authenticated %}
  <div style="text-align:left">
      <form action="{% url 'review_comment_create' pk=review.id %}" method='POST'>
    {% csrf_token %}
    <textarea class="reply" name='text'></textarea>
    <button style="text-align:right; margin-bottom: 15px" type="submit" class="btn btn-primary">
      댓글 쓰기
    </button>
      </form>
  </div>
    {% endif %}
</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy;</p>
  </div>
  <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</body>

</html>