NewBieTonTeam5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('custom_auth.urls')),
    path('', include('greeting.urls')),
    #path(summernote/', include('django_summernote.urls')),
    path('market/', include('puppy_sale.urls')),
    path('community/', include('community.urls')),
]

greeting/urls.py
from django.urls import path

from .views import welcome
from .views import signup
from .views import main

urlpatterns = [
    path('', welcome, name='welcome'),
    path('main/', main, name='main'),
    path('signup/', signup, name='signup'),
]

puppy_sale/urls.py
from django.urls import path
from .views import (PetTransactionCreateView, PetSupplyTransactionCreateView)
                     
urlpatterns = [
#    path('sales/pet', )
    path('pets/new', PetTransactionCreateView.as_view(), name="pet_transactions_create"),
    path('pet_supplies/new', PetSupplyTransactionCreateView.as_view(), name="pet_supply_transactions_create"),
]

puppy_sale/models.py
from django.conf import settings 
from django.db import models

from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
    
class Transaction(models.Model):
    """
    class Transaction
    
    사용자 간의 거래를 나타내는 모델    
    ## 
    
    ## 거래 정보
    * transactable_type : 거래의 종류를 나타내는 정보
    * transactable_object : 무엇을 거래하는지 나타내는 정보
    * price : 거래 가격
    * completed : 거래 완료 여부    
    * deadline : 언제까지 거래할 것인지 정보
    
    ## 거래의 세부 정보
    * description
    
    """    
    transactable_id = models.PositiveIntegerField(default=1)
    transactable_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    transactable_name = models.CharField(max_length=30, default="")
    transactable = GenericForeignKey('transactable_type', 'transactable_id') 
    price = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)    
    deadline = models.DateField(blank=False, null=False)
         
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    owner_name = models.CharField(max_length=30, default="yourname")
    owner_address = models.CharField(max_length=2, blank=False, null=False)
    
    description = models.TextField(blank=False, null=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
class TransactionRequest(models.Model):
    """
    class TransactionRequest
    거래(Transaction) 요청을 나타내는 모델
    """
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    
    requester = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    requester_name = models.CharField(max_length=30, blank=False, null=False)
    
    comment = models.TextField(blank=False, null=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    
# Create your models here.
class Pet(models.Model):
    """
    class Pet
    반려동물의 정보를 나타내는 모델
    * name  : 반려동물의 이름
    * breed : 반려동물의 품종
    * birth_date : 반려동물의 생년월일
    * owner : 반려동물의 소유주
    * owner_name : 반려동물 소유주 이름
    * personality : 반려동물의 성격
    """
    name  = models.CharField(max_length=30, blank=False, null=False)
    breed = models.CharField(max_length=30, blank=False, null=False)
    birth_date = models.DateField(blank=False, null=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    owner_name = models.CharField(max_length=30, default="yourname")
    personality = models.CharField(max_length=20, blank=False)
    transactions = GenericRelation(Transaction)

    
class PetSupply(models.Model):
    """ 
    class PetSupply    
    애완용품을 나타내는 정보
    
    """
    name = models.CharField(max_length=30, blank=False, null=False)
    description  = models.TextField(blank=False, null=False)
    transactions = GenericRelation(Transaction)
    
    class Meta:
        db_table = "pet_supplies"

puppy_sale/views.py
from django.shortcuts import render

from django import forms

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.views.generic import ListView

from django.contrib.contenttypes.models import ContentType

from .models import Transaction, Pet, PetSupply, TransactionRequest
# Create your views here.

class PetTransactionListView(ListView):
    model = Transaction
    paginate_by = 20
    context_object_name = 'pet_list'
    template_name = "puppy_sale/pet_transaction.html"
    
    queryset = Transaction.objects.filter(transactable_type__model='Pet')

class PetSupplyTransactionListView(ListView):
    model = Transaction
    paginate_by = 20
    template_name = "puppy_sale/pet_supply_transaction.html"
    context_object_name = 'pet_supply_list'
    
    queryset = Transaction.objects.filter(transactable_type__model='PetSupply')

    
class PetTransactionCreateView(LoginRequiredMixin, CreateView):
    model = Transaction
    template_name = "puppy_sale/pet_transaction_create.html"
    success_url = '/sales/pets'
    
    fields = ['transactable_id', 'transactable_name', 'price', 'deadline', 'description']
        
    
    def get_form(self, *args, **kwargs):
        form = super(PetTransactionCreateView, self).get_form(*args, **kwargs)
        form.fields['transactable_id'] = \
            forms.ChoiceField(choices=[
                (pet.pk, pet.name) for pet in Pet.objects.filter(owner=self.request.user)])
        form.fields['transactable_name'].widget = forms.HiddenInput()

        return form
    
    def form_valid(self, form):
        form.instance.transactable_type = ContentType.objects.get_for_model(Pet)
        
        form.instance.owner = self.request.user
        form.instance.owner_name = self.request.user.real_name
        form.instance.owner_address = self.request.user.address1
        
        return super().form_valid(form)
    

class PetSupplyTransactionCreateView(LoginRequiredMixin, CreateView):
    model = Transaction
    template_name = "puppy_sale/pet_supply_transaction_create.html"
    success_url = '/sales/pet_supplies'
    
    fields = ['transactable_id', 'transactable_name', 'price', 'deadline', 'description']
        
    
    def get_form(self, *args, **kwargs):
        form = super(PetSupplyTransactionCreateView, self).get_form(*args, **kwargs)
        form.fields['transactable_id'] = \
            forms.ChoiceField(choices=[
                (pet_supply.pk, pet_supply.name) for pet_supply in PetSupply.objects.all()])
        form.fields['transactable_name'].widget = forms.HiddenInput()

        return form
    
    def form_valid(self, form):
        form.instance.transactable_type = ContentType.objects.get_for_model(PetSupply)
        
        form.instance.owner = self.request.user
        form.instance.owner_name = self.request.user.real_name
        form.instance.owner_address = self.request.user.address1
        
        return super().form_valid(form)
    
class TransactionRequestListView(ListView):
    model = TransactionRequest
    paginate_by = 10
    
class PetDetailView(object):
    pass 

class PetSupplyDetailView(object):
    pass

puppy_sale/templates/puppy_sale/pet_supply_transaction_create.html
<head>
    <!-- stylesheets -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">

        <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
        <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <style>
        .container {
            text-align: center;
            margin: 100px;
            border: 1px solid black;
            padding : 30px;
            font-size : 25px;
        }
        
        .container p {
            
        }
        
        .btn {
            width:100%;
        }
    </style>
    
</head>

<body>
    
<form action="{% url 'pet_supply_transactions_create' %}" method='POST'>
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
    </div>
    <div class="btn">
        <button type="submit">
            제출
        </button>   
    </div>
    
</form>

<script>
$(document).ready(function() {
    var hidden_value = $( "#id_transactable_id option:selected" ).text();
    $("#id_transactable_name").val(hidden_value);
    
    $("#id_deadline").datepicker({
        dateFormat: 'yy-mm-dd',
        prevText: '이전 달',
        nextText: '다음 달'
    });
    
    $( "#id_transactable_id" ).change(function() {
        var hidden_value = $( "#id_transactable_id option:selected" ).text();
        $("#id_transactable_name").val(hidden_value);
    });
})
</script>
</body>

puppy_sale/templates/puppy_sale/pet_transaction_create.html
<head>
    <!-- stylesheets -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">

        <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
        <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>

<body>
    
<form action="{% url 'pet_transactions_create' %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
        제출
    </button>
</form>

<script>
$(document).ready(function() {
    var hidden_value = $( "#id_transactable_id option:selected" ).text();
    $("#id_transactable_name").val(hidden_value);
    
    $("#id_deadline").datepicker({
        dateFormat: 'yy-mm-dd',
        prevText: '이전 달',
        nextText: '다음 달'
    });
    
    $( "#id_transactable_id" ).change(function() {
        var hidden_value = $( "#id_transactable_id option:selected" ).text();
        $("#id_transactable_name").val(hidden_value);
    });
})
</script>
</body>